---
services:
  kavita:
    image: docker.io/jvmilazz0/kavita:latest
    container_name: kavita
    hostname: kavita
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - ${KAVITA_PORT}:5000/tcp
    volumes:
      - $HOME/containers/storage/kavita/config:/kavita/config:rw,Z
      - /mnt/hdd/books:/books:ro,z
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - proxy
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - logging=promtail
      - logging_jobname=containerlogs
      - traefik.enable=true
      - traefik.http.routers.kavita.entrypoints=http
      - traefik.http.routers.kavita.rule=Host(`kavita.${HOST_DOMAIN}`)
      - traefik.http.middlewares.kavita-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.kavita.middlewares=kavita-https-redirect
      - traefik.http.routers.kavita-secure.entrypoints=https
      - traefik.http.routers.kavita-secure.rule=Host(`kavita.${HOST_DOMAIN}`)
      - traefik.http.routers.kavita-secure.tls=true
      - traefik.http.routers.kavita-secure.service=kavita
      - traefik.http.services.kavita.loadbalancer.server.port=5000
      - traefik.docker.network=proxy

networks:
  proxy:
    external: true