---
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    hostname: audiobookshelf
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Stockholm
      - PORT=13378
    volumes:
      - /opt/stacks/audiobookshelf/config:/config:rw
      - /opt/stacks/audiobookshelf/metadata:/metadata:rw
      - /mnt/ssd/media/books:/audiobooks:ro
    ports:
      - 13378:13378/tcp
    user: ${UID:-1000}:${GID:-1000}
    networks:
      - proxy

networks:
  proxy:
    external: true
