---
services:
  gatus:
    image: ghcr.io/twin/gatus:latest
    container_name: gatus
    hostname: gatus
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Stockholm
      - GATUS_CONFIG_PATH=/config
    volumes:
      - /opt/stacks/gatus/config:/config:ro
      - /opt/stacks/gatus/data:/data:rw
    ports:
      - 8081:8080/tcp
    networks:
      - proxy

networks:
  proxy:
    external: true
