---
services:
  gatus:
    image: ghcr.io/twin/gatus:latest
    container_name: gatus
    hostname: gatus
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=${TZ}
      - GATUS_CONFIG_PATH=${GATUS_CONFIG_PATH}
      - GATUS_DB_URL=${GATUS_DB_URL}
      - GATUS_OIDC_CLIENT_ID=${GATUS_OIDC_CLIENT_ID}
      - GATUS_OIDC_CLIENT_SECRET=${GATUS_OIDC_CLIENT_SECRET}
      - GATUS_OIDC_ISSUER_URL=${GATUS_OIDC_ISSUER_URL}
      - GATUS_OIDC_REDIRECT_URL=${GATUS_OIDC_REDIRECT_URL}
      - GATUS_PORT=${GATUS_PORT}
    volumes:
      - /opt/stacks/gatus/config:/config:ro
    ports:
      - 8899:8899/tcp
    networks:
      - proxy

networks:
  proxy:
    external: true
