---
services:
  gatus:
    image: ghcr.io/twin/gatus:latest
    container_name: gatus
    hostname: gatus
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file: .env
    volumes:
      - /opt/stacks/gatus/config:/config:ro
    ports:
      - 8899:8899/tcp
    networks:
      - proxy

networks:
  proxy:
    external: true
