---
services:
  zabbix-backend:
    image: docker.io/zabbix/zabbix-server-pgsql:latest
    container_name: zabbix-backend
    hostname: zabbix-backend
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=${TZ}
      - DB_SERVER_HOST=${DB_SERVER_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - 10051:10051/tcp
    volumes:
      - /opt/stacks/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:rw
      - /opt/stacks/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:rw
      - /opt/stacks/zabbix/export:/var/lib/zabbix/export:rw
      - /opt/stacks/zabbix/snmptraps:/var/lib/zabbix/snmptraps:rw
    networks:
      - proxy

  zabbix-frontend:
    image: docker.io/zabbix/zabbix-web-nginx-pgsql:latest
    container_name: zabbix-frontend
    hostname: zabbix-frontend
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=${TZ}
      - DB_SERVER_HOST=${DB_SERVER_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PHP_TZ=${TZ}
      - ZBX_SERVER_HOST=${ZBX_SERVER_HOST}
    healthcheck:
      disable: true
    ports:
      - 8765:8080/tcp
    volumes:
    depends_on:
      - zabbix-backend
    networks:
      - proxy

  zabbix-agent:
    image: docker.io/zabbix/zabbix-agent2:latest
    container_name: zabbix-agent
    hostname: zabbix-agent
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=${TZ}
      - ZBX_HOSTNAME=${ZBX_HOSTNAME}
      - ZBX_SERVER_HOST=${ZBX_SERVER_HOST}
    volumes:
    depends_on:
      - zabbix-backend
    networks:
      - proxy

networks:
  proxy:
    external: true