---
services:
  mkvtoolnix:
    image: docker.io/jlesage/mkvtoolnix:latest
    container_name: mkvtoolnix
    hostname: mkvtoolnix
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - ${MKVTOOLNIX_PORT}:5800/tcp
    volumes:
      - $HOME/containers/storage/mkvtoolnix/config:/config:rw,Z
      - /mnt/ssd:/storage:rw,z
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - proxy
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - logging=promtail
      - logging_jobname=containerlogs
      - traefik.enable=true
      - traefik.http.routers.mkvtoolnix.entrypoints=http
      - traefik.http.routers.mkvtoolnix.rule=Host(`mkvtoolnix.${HOST_DOMAIN}`)
      - traefik.http.middlewares.mkvtoolnix-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.mkvtoolnix.middlewares=mkvtoolnix-https-redirect
      - traefik.http.routers.mkvtoolnix-secure.entrypoints=https
      - traefik.http.routers.mkvtoolnix-secure.rule=Host(`mkvtoolnix.${HOST_DOMAIN}`)
      - traefik.http.routers.mkvtoolnix-secure.tls=true
      - traefik.http.routers.mkvtoolnix-secure.service=mkvtoolnix
      - traefik.http.services.mkvtoolnix.loadbalancer.server.port=5800
      - traefik.docker.network=proxy

networks:
  proxy:
    external: true