---
services:
  umami:
    image: ghcr.io/umami-software/umami:latest
    container_name: umami
    hostname: umami
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=${TZ}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_TYPE=${DATABASE_TYPE}
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
    ports:
      - 3210:3210/tcp
    volumes:
    networks:
      - proxy

networks:
  proxy:
    external: true
