---
services:
  filebrowser:
    image: docker.io/filebrowser/filebrowser:latest
    container_name: filebrowser
    hostname: filebrowser
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - FB_PASSWORD=${FB_PASSWORD}
      - FB_USERNAME=${FB_USERNAME}
    healthcheck:
      disable: true
    ports:
      - 8005:8005/tcp
    volumes:
      - $HOME/containers/storage/filebrowser/config:/config:rw
      - $HOME/containers/storage/filebrowser/database:/database:rw
      - /:/srv:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - proxy
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - logging=promtail
      - logging_jobname=containerlogs

networks:
  proxy:
    external: true