---
services:
  zabbix-backend:
    image: docker.io/zabbix/zabbix-server-pgsql:latest
    container_name: zabbix-backend
    hostname: zabbix-backend
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file: .env
    volumes:
      - /opt/stacks/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:rw
      - /opt/stacks/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:rw
      - /opt/stacks/zabbix/export:/var/lib/zabbix/export:rw
      - /opt/stacks/zabbix/snmptraps:/var/lib/zabbix/snmptraps:rw
    ports:
      - 10051:10051/tcp
    networks:
      - proxy

  zabbix-frontend:
    image: docker.io/zabbix/zabbix-web-nginx-pgsql:latest
    container_name: zabbix-frontend
    hostname: zabbix-frontend
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file: .env
    ports:
      - 8765:8080/tcp
    healthcheck:
      disable: true
    depends_on:
      - zabbix-backend
    networks:
      - proxy

  zabbix-agent:
    image: docker.io/zabbix/zabbix-agent2:latest
    container_name: zabbix-agent
    hostname: zabbix-agent
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file: .env
    depends_on:
      - zabbix-backend
    networks:
      - proxy

networks:
  proxy:
    external: true
