---
services:
  arcane:
    image: ghcr.io/getarcaneapp/manager:latest
    container_name: arcane
    hostname: arcane
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file: .env
    volumes:
      - /opt/stacks/arcane/data:/app/data:rw
      - /opt/stacks:/opt/stacks:rw
      - /mnt/ssd/backup:/backups:rw
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3552:3552/tcp
    healthcheck:
      disable: true
    group_add: [987]
    networks:
      - proxy

networks:
  proxy:
    external: true
