---
services:
  gitea:
    image: ghcr.io/go-gitea/gitea:latest-rootless
    container_name: gitea
    hostname: gitea
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file: .env
    volumes:
      - /opt/stacks/gitea/config:/etc/gitea:rw
      - /opt/stacks/gitea/data:/var/lib/gitea:rw
    ports:
      - 3002:3002/tcp
      - 2222:2222/tcp
    networks:
      - proxy

networks:
  proxy:
    external: true
