---
services:
  gotify:
    image: ghcr.io/gotify/server:latest
    container_name: gotify
    hostname: gotify
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file: .env
    volumes:
      - /opt/stacks/gotify/config:/app/data:rw
    ports:
      - 8001:8001/tcp
    healthcheck:
      disable: true
    user: ${UID:-1000}:${GID:-1000}
    networks:
      - proxy

networks:
  proxy:
    external: true
