---
services:
  navidrome:
    image: docker.io/deluan/navidrome:latest
    container_name: navidrome
    hostname: navidrome
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Stockholm
      - PUID=1000
      - PGID=1000
    ports:
      - 4533:4533/tcp
    volumes:
      - $HOME/containers/storage/navidrome/data:/data:rw,Z
      - /mnt/hdd/music:/music:ro,z
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - proxy
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - logging=promtail
      - logging_jobname=containerlogs

networks:
  proxy:
    external: true