---
services:
  traefik:
    image: ghcr.io/traefik/traefik:latest
    container_name: traefik
    hostname: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file: .env
    volumes:
      - /opt/stacks/traefik/config:/etc/traefik:ro
      - /opt/stacks/traefik/data:/data:rw
      - /opt/stacks/traefik/log:/var/log/traefik:rw
    ports:
      - 80:80/tcp
      - 443:443/tcp
    networks:
      - proxy

networks:
  proxy:
    external: true
