---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - ${RADARR_PORT}:7878/tcp
    volumes:
      - $HOME/containers/storage/radarr/config:/config:rw,Z
      - /mnt/ssd:/data:rw,z
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - proxy
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - logging=promtail
      - logging_jobname=containerlogs
      - traefik.enable=true
      - traefik.http.routers.radarr.entrypoints=http
      - traefik.http.routers.radarr.rule=Host(`radarr.${HOST_DOMAIN}`)
      - traefik.http.middlewares.radarr-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.radarr.middlewares=radarr-https-redirect
      - traefik.http.routers.radarr-secure.entrypoints=https
      - traefik.http.routers.radarr-secure.rule=Host(`radarr.${HOST_DOMAIN}`)
      - traefik.http.routers.radarr-secure.tls=true
      - traefik.http.routers.radarr-secure.service=radarr
      - traefik.http.services.radarr.loadbalancer.server.port=7878
      - traefik.docker.network=proxy

networks:
  proxy:
    external: true