---
services:
  pgadmin:
    image: docker.io/dpage/pgadmin4:latest
    container_name: pgadmin
    hostname: pgadmin
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file: .env
    volumes:
      - /opt/stacks/pgadmin/data:/var/lib/pgadmin
    ports:
      - 5050:80/tcp
    networks:
      - proxy

networks:
  proxy:
    external: true
