---
services:
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless
    hostname: paperless
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file: .env
    volumes:
      - /opt/stacks/paperless/consume:/usr/src/paperless/consume:rw
      - /opt/stacks/paperless/data:/usr/src/paperless/data:rw
      - /opt/stacks/paperless/export:/usr/src/paperless/export:rw
      - /opt/stacks/paperless/media:/usr/src/paperless/media:rw
    ports:
      - 8124:8124/tcp
    healthcheck:
      disable: true
    networks:
      - proxy

networks:
  proxy:
    external: true
