---
services:
  jellystat:
    image: ghcr.io/cyfershepard/jellystat:latest
    container_name: jellystat
    hostname: jellystat
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    env_file: .env
    volumes:
      - /opt/stacks/jellystat/data:/app/backend/backup-data:rw
    ports:
      - 3498:3000/tcp
    healthcheck:
      disable: true
    networks:
      - proxy

networks:
  proxy:
    external: true
