---
services:
  jellystat:
    image: ghcr.io/cyfershepard/jellystat:latest
    container_name: jellystat
    hostname: jellystat
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    environment:
      - TZ=${TZ}
      - JWT_SECRET=${JWT_SECRET}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_IP=${POSTGRES_IP}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - /opt/stacks/jellystat/data:/app/backend/backup-data
    ports:
      - 3498:3000/tcp
    healthcheck:
      disable: true
    networks:
      - proxy

networks:
  proxy:
    external: true
