---
services:
  redis:
    image: docker.io/library/redis:latest
    container_name: redis
    hostname: redis
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Stockholm
    volumes:
      - /opt/stacks/redis/data:/data:rw
    networks:
      - proxy

  immich:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich
    hostname: immich
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file: .env
    volumes:
      - /opt/stacks/immich/upload:/usr/src/app/upload:rw
      - /opt/stacks/immich/data:/data:rw
      - /mnt/hdd/photos:/usr/src/app/photos:ro
    ports:
      - 2283:2283/tcp
    depends_on:
      - redis
    networks:
      - proxy

networks:
  proxy:
    external: true
