---
services:
  phpmyadmin:
    image: docker.io/phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    hostname: phpmyadmin
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    ports:
      - 8765:80/tcp
    volumes:
      - $HOME/containers/storage/phpmyadmin/apache2.conf:/etc/apache2/apache2.conf:ro
      - $HOME/containers/storage/phpmyadmin/sessions:/sessions:rw
      - $HOME/containers/storage/phpmyadmin/themes/boodark-nord:/var/www/html/themes/boodark-nord:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy
    labels:
      - logging=promtail
      - logging_jobname=containerlogs

networks:
  proxy:
    external: true