---
services:
  dozzle:
    image: ghcr.io/amir20/dozzle:latest
    container_name: dozzle
    hostname: dozzle
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file: .env
    volumes:
      - /opt/stacks/dozzle/data:/data:rw
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8008:8008/tcp
    networks:
      - proxy

networks:
  proxy:
    external: true
