---
services:
  memos:
    image: ghcr.io/usememos/memos:stable
    container_name: memos
    hostname: memos
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file: .env
    volumes:
      - /opt/stacks/memos/config:/var/opt/memos:rw
    ports:
      - 5230:5230/tcp
    networks:
      - proxy

networks:
  proxy:
    external: true
