---
services:
  dockhand:
    image: docker.io/fnsys/dockhand:latest
    container_name: dockhand
    hostname: dockhand
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Stockholm
      - PUID=1000
      - PGID=1000
      - PORT=3003
    group_add:
      - "987"
    healthcheck:
      disable: true
    ports:
      - 3003:3003/tcp
    volumes:
      - /opt/stacks/dockhand/data:/app/data:rw
      - /opt/stacks:/opt/stacks:rw
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy

networks:
  proxy:
    external: true
