---
services:
  glance:
    image: docker.io/glanceapp/glance:latest
    container_name: glance
    hostname: glance
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Stockholm
    ports:
      - 8087:8087/tcp
    volumes:
      - $HOME/containers/storage/glance/config:/app/config:rw,Z
      - $HOME/containers/storage/glance/icons:/app/assets:rw,Z
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - proxy
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - logging=promtail
      - logging_jobname=containerlogs

networks:
  proxy:
    external: true